# Generated by Django 2.2.5 on 2019-11-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerobox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=100)),
                ('lon', models.FloatField(blank=True)),
                ('lat', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AeroboxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=100)),
                ('pm', models.FloatField(blank=True)),
                ('temp', models.FloatField(blank=True)),
                ('rh', models.IntegerField(blank=True)),
                ('co2', models.IntegerField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('aerobox', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aerobox_api.Aerobox')),
            ],
        ),
    ]
