# Generated by Django 2.2.7 on 2019-11-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerobox_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='p_k',
            field=models.CharField(blank=True, default='b5718d1d9e4389ad5baaa46bd90a697c', max_length=33, unique=True),
        ),
    ]
