# Generated by Django 2.2.5 on 2019-11-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aerobox_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('aerobox_data', models.ManyToManyField(to='aerobox_api.AeroboxData')),
                ('user', models.ManyToManyField(to='aerobox_api.UserExtension')),
            ],
        ),
    ]
